FROM gradle

COPY . /app

USER root

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" >> /etc/timezone

ENV JAVA_OPTS ''

WORKDIR /app

RUN gradle bJ

EXPOSE 10083

ENTRYPOINT java $JAVA_OPTS -jar build/libs/test-web-app-0.0.1-SNAPSHOT.jar
