server:
  port: 10083
spring:
  application:
    name: test-web
  webflux:
    static-path-pattern: /static/**
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://all-in-one-dev.dmptesting.xyz:8761/eureka/}
    registry-fetch-interval-seconds: 5
    enabled: ${EUREKA_ENABLE:true}