server:
  port: 10084
  tomcat:
    max-connections: 1000
    max-threads: 120

spring:
  application:
    name: test-web
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: false
  instance:
    prefer-ip-address: true

system:
  pause: 5
